### ISSUE TITLE
在mac上安装客户端失败，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [hmgle/socks5_go#1]
hi.

yudeMacBook-Air:gopath brite$ ~/go/bin/go get -u -v github.com/hmgle/socks5_go/cmd/socks5-local
github.com/hmgle/socks5_go (download)
github.com/hmgle/tcfs-go (download)
github.com/hmgle/tcfs-go
# github.com/hmgle/tcfs-go
src/github.com/hmgle/tcfs-go/tcfs.go:88: undefined: getattrHandle
src/github.com/hmgle/tcfs-go/tcfs.go:166: undefined: utimeHandle
yudeMacBook-Air:gopath brite$

**Comment by hmgle** [comment]
之前依赖的 [tcfs-go](https://github.com/hmgle/tcfs-go) 不支持 Darwin, 现已更新，可以重新执行 `go get -u -v github.com/hmgle/socks5_go/cmd/socks5-local` 试试。

**Comment by luckypoem** [comment]
hi.

现在 才看到你的回复。在mac上安装客户端成功。不过我看到加密方式只支持rc4. 但是rc4不是早就被破解了吗？可否考虑升级一下，支持其他的加密方式，比如aes-256-cfb?

**Comment by hmgle** [comment]
> hi.
> 
> 现在 才看到你的回复。在mac上安装客户端成功。不过我看到加密方式只支持rc4. 但是rc4不是早就被破解了吗？可否考虑升级一下，支持其他的加密方式，比如aes-256-cfb?

我自己也不使用这个它，而是选择更流行、更安全的工具。所以目前没有升级的计划。
